GET http://localhost:8080/users HTTP/1.1

###
GET http://localhost:8080/users/65b012f47d46606bfb85b15e HTTP/1.1

###
DELETE http://localhost:8080/users/65b012f47d46606bfb85b15e HTTP/1.1

###
POST http://localhost:8080/user HTTP/1.1
content-type: application/json

{
    "name": "Test_5",
    "gender": "male",
    "age": 13
}